linters:
  disable:
    - contextcheck
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - gci
    - goerr113
    - golint
    - ifshort
    - interfacer
    - lll
    - maligned
    - nosnakecase
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - varcheck
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  enable-all: true
